apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dungeonomics.fullname" . }}-admin
type: Opaque
stringData:
  DJANGO_SUPERUSER_USERNAME: {{ .Values.admin.username | quote }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.admin.email | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.admin.password | quote }}